# config/default.yaml
# Default configuration for Vulnerability Manager

server:
  host: "0.0.0.0"
  port: 8080

database:
#  url: "postgres://vlnman:DogNET@localhost:54321/vulnerability_manager"
#  max_connections: 50
# ======= DIVERSE CONFIG ====== #
  url: "postgresql:///vulnerability_manager?user=vlnman&password=DogNET&host=/var/run/postgresql"
  max_connections: 30
  connection_timeout_seconds: 10
  idle_timeout_seconds: 600
  max_lifetime_seconds: 1800

auth:
  secret_key: 'QMowkY8luJr8H7PaqeNOl5pSrDqDD1ShxAT3dxc/Buq4pMhsmJX+y8fp8C8ra5HkZ7foeXrZWA=='
  token_duration_hours: 24
  password_policy:
    min_length: 8
    max_length: 128
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    special_chars: "!@#$%^&*()_+-=[]{}|;:,.<>?"
    prevent_common_passwords: true

plugins:
  directory: "./plugins"
  enabled: false

log:
  level: "info"
  file: null

network:
  interface: "wlp0s20f3"  # Default network interface for scanning (change to your interface, e.g., wlan0, enp0s3)
  default_scan_timeout: 500  # Timeout in milliseconds
  max_scan_workers: 50  # Maximum concurrent scan workers
